# Generated by Django 5.0.6 on 2024-06-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='192.168.88.254', max_length=15)),
                ('port', models.IntegerField(default=502)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('in', 'Input'), ('out', 'Output')], max_length=3)),
                ('port', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=False)),
                ('program_number', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_number', models.IntegerField(default=0)),
                ('program_acknowledge', models.IntegerField(default=0)),
                ('Prog0', models.BooleanField(default=False)),
                ('Prog1', models.BooleanField(default=False)),
                ('Prog2', models.BooleanField(default=False)),
                ('Prog3', models.BooleanField(default=False)),
                ('Prog4', models.BooleanField(default=False)),
                ('Prog5', models.BooleanField(default=False)),
                ('Prog6', models.BooleanField(default=False)),
                ('Prog7', models.BooleanField(default=False)),
                ('ResRs', models.BooleanField(default=False)),
                ('ResF', models.BooleanField(default=False)),
                ('ProgAck0', models.BooleanField(default=False)),
                ('ProgAck1', models.BooleanField(default=False)),
                ('ProgAck2', models.BooleanField(default=False)),
                ('ProgAck3', models.BooleanField(default=False)),
                ('ProgAck4', models.BooleanField(default=False)),
                ('ProgAck5', models.BooleanField(default=False)),
                ('ProgAck6', models.BooleanField(default=False)),
                ('ProgAck7', models.BooleanField(default=False)),
                ('Rdy', models.BooleanField(default=False)),
                ('NF', models.BooleanField(default=False)),
                ('CyCmp', models.BooleanField(default=False)),
                ('Ok', models.BooleanField(default=False)),
                ('InCy', models.BooleanField(default=False)),
                ('', models.BooleanField(default=False)),
                ('EnAck', models.BooleanField(default=False)),
            ],
        ),
    ]
