# Generated by Django 5.0.6 on 2024-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='192.168.88.254', max_length=15)),
                ('port', models.IntegerField(default=502)),
            ],
        ),
        migrations.CreateModel(
            name='SignalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('clockwise', models.BooleanField(default=False)),
                ('counter_clockwise', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('ok', models.BooleanField(default=False)),
                ('nok', models.BooleanField(default=False)),
                ('in_cycle', models.BooleanField(default=False)),
                ('cycle_complete', models.BooleanField(default=False)),
                ('program_number', models.IntegerField(default=0)),
            ],
        ),
    ]
