# Generated by Django 5.0.6 on 2024-06-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus_app', '0002_alter_modbusconfig_id_alter_signal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalstate',
            name='Ccw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signalstate',
            name='Cw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signalstate',
            name='En',
            field=models.BooleanField(default=False),
        ),
    ]
