# Generated by Django 5.0.6 on 2024-06-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modbus_app', '0003_signalstate_ccw_signalstate_cw_signalstate_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalstate',
            name='Ccw',
        ),
        migrations.RemoveField(
            model_name='signalstate',
            name='Cw',
        ),
    ]
